// Code generated by tygo. DO NOT EDIT.
// Code generated by tygo from pkg/api/*.go. DO NOT EDIT.
// Regenerate via: tygo generate (config: pkg/api/tygo.yaml)

//////////
// source: backups.go

/**
 * Backup is the static configuration for one backup job. Mirrors the
 * daemon's services.yaml `backups:` section.
 */
export interface Backup {
  unit: string;
  enabled: boolean;
  schedule: string; // cron expression
  depends_on: string[];
  requires_mount: string[];
  healthcheck_uuid: string;
  pause_service: string;
}
/**
 * BackupStatus is the runtime status emitted by GET /api/v1/backups.
 * Embeds Backup so all static config fields are present too.
 */
export interface BackupStatus {
  Backup: Backup;
  active_state: string;
  result: string;
  last_run_start: string;
  last_run_end: string;
  next_run: string;
}
/**
 * PatchBackupRequest is the body for PATCH /api/v1/backups/{unit}.
 */
export interface PatchBackupRequest {
  enabled?: boolean;
  schedule?: string;
  healthcheck_uuid?: string;
  pause_service?: string;
  depends_on?: string[];
}
/**
 * PatchBackupResponse is the result of PATCH /api/v1/backups/{unit}.
 */
export interface PatchBackupResponse {
  success: boolean;
  backup: Backup;
}

//////////
// source: common.go

/**
 * SuccessResponse is the canonical envelope for mutating endpoints
 * that don't return a typed body. `Success` is always set; `Error` is
 * populated on best-effort failures the handler swallowed (rare —
 * most failures are returned via non-2xx + http.Error instead).
 */
export interface SuccessResponse {
  success: boolean;
  error?: string;
}
/**
 * BulkResult is returned by /api/start-all and /api/stop-all.
 */
export interface BulkResult {
  success: boolean;
  total: number /* int */;
  failed: number /* int */;
}
/**
 * ErrorResponse is the daemon's JSON error body for non-2xx responses.
 */
export interface ErrorResponse {
  error: string;
  message?: string;
  code?: string;
}

//////////
// source: secrets.go

/**
 * SecretEntry mirrors the registry JSON written at activation by
 * modules/secrets.nix to /etc/homelab-secrets-registry.json.
 */
export interface SecretEntry {
  name: string;
  description: string;
  services: string[];
  runPath: string; // e.g. /run/secrets/caddy/CLOUDFLARE_API_TOKEN
}
/**
 * SecretStatus is the response shape for GET /api/v1/secrets[/:name].
 * Embeds SecretEntry so all metadata fields are exposed.
 */
export interface SecretStatus {
  SecretEntry: SecretEntry;
  present: boolean;
  modified_at?: string; // RFC3339; empty if unknown
  preview?: string; // first 3 chars + "•••"
}
/**
 * SecretsListResponse is the body of GET /api/v1/secrets.
 */
export interface SecretsListResponse {
  secrets: SecretStatus[];
  deploy_pending: boolean;
}
/**
 * SecretSetRequest is the body of PUT /api/v1/secrets/{name}.
 */
export interface SecretSetRequest {
  value: string;
}
/**
 * SecretMutationResponse is returned by PUT/DELETE /api/v1/secrets/{name}.
 */
export interface SecretMutationResponse {
  success: boolean;
  deploy_pending: boolean;
}
/**
 * DeployEvent is one frame of the SSE stream from
 * POST /api/v1/secrets/deploy. Frames are JSON-encoded after `data: `.
 */
export interface DeployEvent {
  type: string; // "log" | "error" | "done"
  message: string;
}

//////////
// source: services.go

/**
 * Service is the static configuration for one managed systemd unit.
 * Mirrors the daemon's services.yaml. Emitted by GET /api/v1/config.
 */
export interface Service {
  unit: string;
  enabled: boolean;
  order: number /* int */;
  boot_delay: number /* int */;
  depends_on: string[];
  requires_mount: string[];
  restart: string;
  restart_delay: number /* int */;
}
/**
 * ServiceStatus is the per-unit runtime status emitted by
 * GET /api/v1/status. It is the **superset** of fields the dash and
 * frontend already expect; the daemon populates all of them.
 */
export interface ServiceStatus {
  unit: string;
  enabled: boolean;
  active: boolean;
  active_state: string;
  sub_state: string;
  description: string;
  user_stopped: boolean;
  restart: string;
  order: number /* int */;
  boot_delay: number /* int */;
  restart_delay: number /* int */;
  depends_on: string[];
  requires_mount: string[];
  failure_count: number /* int */; // consecutive failures since last success
  backoff_until: string; // RFC3339; empty if not backing off
  blocked_reason: string; // why the daemon won't start/restart this service
}
/**
 * PatchServiceRequest is the JSON body for PATCH /api/v1/config/{unit}.
 * Pointer fields are tri-state: nil = leave unchanged, &"" = clear.
 */
export interface PatchServiceRequest {
  enabled?: boolean;
  order?: number /* int */;
  boot_delay?: number /* int */;
  depends_on?: string[];
  restart?: string;
  restart_delay?: number /* int */;
}
/**
 * PatchServiceResponse is the result of PATCH /api/v1/config/{unit}.
 */
export interface PatchServiceResponse {
  success: boolean;
  service: Service;
}
/**
 * ServiceInfo is a superset of ServiceStatus that includes update metadata
 * and config fields. It is the single source of truth for the frontend's
 * service table, emitted by the daemon's merged services endpoint.
 */
export interface ServiceInfo {
  name: string;
  type: string; // "Docker" or "Native"
  image?: string;
  active_state: string;
  sub_state: string;
  description: string;
  unit_name: string;
  update_available: boolean;
  current_version?: string;
  remote_version?: string;
  daemon_managed: boolean;
  restart_policy: string;
  boot_order: number /* int */;
  boot_delay: number /* int */;
  restart_delay: number /* int */;
  depends_on: string[];
  user_stopped: boolean;
  daemon_enabled: boolean;
  failure_count: number /* int */;
  backoff_seconds: number /* int */;
  blocked_reason: string; // why the daemon won't start/restart this service
  requires_mount: string[]; // mountpoints that must be present
}

//////////
// source: stats.go

/**
 * StatsSnapshot is a point-in-time host statistics snapshot emitted by the
 * daemon's stats collector and consumed by the dashboard. Every field uses
 * the same JSON tags as the dash's former collector.Stats so the frontend
 * contract is preserved.
 */
export interface StatsSnapshot {
  CPUUsage: number /* float64 */;
  CPUTemp: number /* float64 */;
  NVMeTemp: number /* float64 */;
  MemTotal: number /* uint64 */;
  MemUsed: number /* uint64 */;
  MemPercent: number /* float64 */;
  Disks: DiskStat[];
  NetSentRate: number /* float64 */;
  NetRecvRate: number /* float64 */;
  TopCPU: ProcessStat[];
  TopMem: ProcessStat[];
  System: HostInfo;
  Gpu: GpuStats;
  MemUsedStr: string;
  MemTotalStr: string;
  UptimeStr: string;
}
/**
 * ProcessStat holds top-N process info.
 */
export interface ProcessStat {
  PID: number /* int32 */;
  Name: string;
  CPU: number /* float64 */;
  Memory: number /* float32 */;
}
/**
 * DiskStat holds disk usage for a mount point.
 */
export interface DiskStat {
  Mountpoint: string;
  Total: number /* uint64 */;
  Used: number /* uint64 */;
  Percent: number /* float64 */;
  UsedStr: string;
  TotalStr: string;
}
/**
 * HostInfo holds static + dynamic host metadata.
 */
export interface HostInfo {
  Hostname: string;
  OS: string;
  KernelVersion: string;
  Uptime: number /* uint64 */;
  CPUModel: string;
  CPUCores: number /* int */;
  Motherboard: string;
  Packages: number /* int */;
}
/**
 * GpuStats holds a single Intel iGPU sample.
 */
export interface GpuStats {
  RenderBusy: number /* float64 */;
  VideoBusy: number /* float64 */;
  FreqMHz: number /* float64 */;
  PowerW: number /* float64 */;
  RC6Pct: number /* float64 */;
  Available: boolean;
  ErrMsg: string;
}

//////////
// source: storage.go

/**
 * DiskIOStats are per-device I/O counters from /proc/diskstats.
 */
export interface DiskIOStats {
  device_name: string;
  read_ios: number /* uint64 */; // completed reads
  write_ios: number /* uint64 */; // completed writes
  read_sectors: number /* uint64 */; // sectors read
  write_sectors: number /* uint64 */; // sectors written
  io_in_progress: number /* uint64 */; // currently in-flight I/Os
}
/**
 * PoolUsage is reported by `bcachefs fs usage`.
 */
export interface PoolUsage {
  total_bytes: number /* uint64 */;
  used_bytes: number /* uint64 */;
  available_bytes: number /* uint64 */;
  used_percent: number /* float64 */;
}
/**
 * Disk is one physical device inside a Pool (or in Unassigned).
 */
export interface Disk {
  name: string;
  path: string;
  size: number /* uint64 */;
  type: string;
  model: string;
  serial: string;
  fstype: string;
  mountpoint: string;
  label: string;
  has_children?: boolean;
  bcachefs_label: string;
  data_target: string;
  metadata_target: string;
  io?: DiskIOStats;
  friendly_name: string;
}
/**
 * Pool is one bcachefs pool with its member disks.
 */
export interface Pool {
  uuid: string;
  name: string;
  state: string; // "mounted" | "unmounted"
  mountdir: string;
  label: string;
  data_replicas: number /* int */;
  metadata_replicas: number /* int */;
  disks: Disk[];
  usage?: PoolUsage;
}
/**
 * Subvolume is one bcachefs subvolume below a mounted Pool.
 */
export interface Subvolume {
  id: string;
  path: string;
  used_bytes: number /* int64 */; // -1 if not yet calculated
}
/**
 * StorageStatus is the body of GET /api/v1/storage.
 */
export interface StorageStatus {
  pools: Pool[];
  unassigned: Disk[];
  subvolumes: Subvolume[];
}
/**
 * StoragePoolConfig is the user-managed config (auto-mount etc.) for
 * one pool, keyed by UUID. Serialised in services.yaml under storage.pools.
 */
export interface StoragePoolConfig {
  uuid: string;
  mountpoint: string;
  options: string;
  auto_mount: boolean;
  name?: string;
}
/**
 * MountRequest — POST /api/v1/storage/mount.
 */
export interface MountRequest {
  devices: string[];
  mountpoint: string;
}
/**
 * UnmountRequest — POST /api/v1/storage/unmount.
 */
export interface UnmountRequest {
  mountpoint: string;
}
/**
 * CheckRequest — POST /api/v1/storage/check.
 */
export interface CheckRequest {
  devices: string[];
  mountdir: string;
  fix: boolean;
}
/**
 * BalanceRequest — POST /api/v1/storage/balance.
 */
export interface BalanceRequest {
  mountdir: string;
}
/**
 * SubvolumeUsageRequest — POST /api/v1/storage/subvolume-usage.
 */
export interface SubvolumeUsageRequest {
  paths: string[];
}
/**
 * SubvolumeUsageResponse is the body of POST /api/v1/storage/subvolume-usage.
 */
export interface SubvolumeUsageResponse {
  success: boolean;
  usage: { [key: string]: number /* int64 */};
}
/**
 * StorageConfigPatch — PATCH /api/v1/storage/config.
 */
export interface StorageConfigPatch {
  pools: StoragePoolConfig[];
}
/**
 * SubvolumeRequest — POST /api/v1/storage/subvolume.
 */
export interface SubvolumeRequest {
  path: string;
}
/**
 * InitFoldersRequest — POST /api/v1/storage/init-folders.
 */
export interface InitFoldersRequest {
  mountpoint: string;
}
/**
 * CommandResult is the envelope returned by the storage commands that
 * also surface their stdout/stderr (check, balance).
 */
export interface CommandResult {
  success: boolean;
  error?: string;
  output: string;
}
/**
 * UnmountConflict is returned with HTTP 409 when active services
 * depend on a mountpoint that the user asked to unmount.
 */
export interface UnmountConflict {
  error: string;
  message: string;
  active_deps: string[];
}

//////////
// source: updates.go

/**
 * UpdateInfo is per-container update state.
 */
export interface UpdateInfo {
  has_update: boolean;
  current_version: string;
  remote_version: string;
  local_id: string;
  remote_id: string;
}
/**
 * MetadataEntry is per-container static metadata (image, description, link).
 */
export interface MetadataEntry {
  image: string;
  description: string;
  revision_url: string;
}
/**
 * UpdatesStatus is the body of GET /api/v1/updates.
 */
export interface UpdatesStatus {
  updates: { [key: string]: UpdateInfo};
  metadata: { [key: string]: MetadataEntry};
}

//////////
// source: version.go
/*
Package api is the shared wire contract between homelab-daemon and
homelab-dash. It deliberately depends only on the standard library so
that both consumers can import it cheaply and so that types can be
machine-translated to TypeScript via tygo (see tygo.yaml).

The contract is intentionally minimal: just JSON-tagged struct
definitions plus a handful of constants. Behaviour (HTTP handlers,
the typed client) lives in the consumers.
*/

/**
 * Version is the wire-contract version. Bump on breaking JSON changes.
 */
export const Version = "v1";
/**
 * APIPrefix is the route prefix for versioned endpoints.
 * During the transition both /api/... and /api/v1/... are served.
 */
export const APIPrefix = "/api/" + Version;
/**
 * SocketPath is the canonical unix-socket path the daemon listens on.
 * Centralised here to avoid divergence across modules + Nix.
 */
export const SocketPath = "/run/homelab-daemon/daemon.sock";
/**
 * VersionResponse is the body of GET /api/version.
 */
export interface VersionResponse {
  version: string;
  apiVersion: string;
  prefix: string;
}

//////////
// source: vms.go

/**
 * VMInfo is the body of GET /api/v1/vms (one element per VM).
 */
export interface VMInfo {
  name: string;
  state: string;
  memory: string; // human-readable, e.g. "4.0 GB"
  cpus: number /* uint */;
}
/**
 * Canonical VM-state strings, mirrored on the frontend.
 */
export const VMStateRunning = "Running";
/**
 * Canonical VM-state strings, mirrored on the frontend.
 */
export const VMStatePaused = "Paused";
/**
 * Canonical VM-state strings, mirrored on the frontend.
 */
export const VMStateShutOff = "Shut Off";
/**
 * Canonical VM-state strings, mirrored on the frontend.
 */
export const VMStateShuttingDown = "Shutting Down";
/**
 * Canonical VM-state strings, mirrored on the frontend.
 */
export const VMStateCrashed = "Crashed";
/**
 * Canonical VM-state strings, mirrored on the frontend.
 */
export const VMStateNoState = "No State";
/**
 * Canonical VM-state strings, mirrored on the frontend.
 */
export const VMStateBlocked = "Blocked";
/**
 * Canonical VM-state strings, mirrored on the frontend.
 */
export const VMStatePMSuspended = "PM Suspended";
/**
 * Canonical VM-state strings, mirrored on the frontend.
 */
export const VMStateUnknown = "Unknown";
